version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
    environment:
      NK_HOST: root@nkmun.cn
      BUILD_PREFIX: hi-nkmun-backend
      SSH_OPTS: 'UserKnownHostsFile=.circleci/ssh_hosts'
      PRODUCTION_TARGET: deploy-hi-nkmun.sh
      TEST_TARGET: deploy-test-hi-nkmun.sh

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Preperation
          command: |
            echo 'export TAG="${BUILD_PREFIX}:$(git rev-parse --short HEAD)"' >> $BASH_ENV
            echo 'export TARGET="$( [ $CIRCLE_BRANCH == master ] && echo $PRODUCTION_TARGET || echo $TEST_TARGET )"' >> $BASH_ENV
      - run:
          name: Build Docker Image
          command: docker build -t ${TAG} .
      - run:
          name: Push to Server
          command: docker save ${TAG} | gzip -9 | ssh -o ${SSH_OPTS} ${NK_HOST} "gunzip | docker load"
      - run:
          name: Deploy
          command: ssh -o ${SSH_OPTS} ${NK_HOST} "/root/docker/${TARGET} ${TAG}"
